///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChecktheAvailabilityoftheModifiedpowerfield recording.
    /// </summary>
    [TestModule("5e3e7801-32e2-4681-9a5d-67e72dbced14", ModuleType.Recording, 1)]
    public partial class ChecktheAvailabilityoftheModifiedpowerfield : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static ChecktheAvailabilityoftheModifiedpowerfield instance = new ChecktheAvailabilityoftheModifiedpowerfield();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChecktheAvailabilityoftheModifiedpowerfield()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChecktheAvailabilityoftheModifiedpowerfield Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>Modified Power:</n>') on item 'MainWindow.PnlUserControlCollection.LblModifiedPower'.", repo.MainWindow.PnlUserControlCollection.LblModifiedPowerInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.LblModifiedPowerInfo, "Text", "<n>Modified Power:</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Computed') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "Computed");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
