///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DesignTypeSuperiority recording.
    /// </summary>
    [TestModule("c5661497-c07b-418e-a1dc-74deb7c7f8d3", ModuleType.Recording, 1)]
    public partial class DesignTypeSuperiority : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static DesignTypeSuperiority instance = new DesignTypeSuperiority();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DesignTypeSuperiority()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DesignTypeSuperiority Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>&Design Type:</n>') on item 'MainWindow.LblTrialType'.", repo.MainWindow.LblTrialTypeInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainWindow.LblTrialTypeInfo, "Text", "<n>&Design Type:</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Superiority') on item 'MainWindow.CmbTrialType'.", repo.MainWindow.CmbTrialTypeInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.CmbTrialTypeInfo, "Text", "Superiority");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedItem='Superiority') on item 'MainWindow.CmbTrialType'.", repo.MainWindow.CmbTrialTypeInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.CmbTrialTypeInfo, "SelectedItem", "Superiority");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
