///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GiveValuesInThePowerField recording.
    /// </summary>
    [TestModule("8c675f85-877c-4cbf-b544-c67295e8f152", ModuleType.Recording, 1)]
    public partial class GiveValuesInThePowerField : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static GiveValuesInThePowerField instance = new GiveValuesInThePowerField();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GiveValuesInThePowerField()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GiveValuesInThePowerField Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlCommonParameters.TxtPower' at 51;7.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(0));
            repo.MainWindow.PnlCommonParameters.TxtPower.Click("51;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(1));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.BtnCompute' at 46;16.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(2));
            repo.MainWindow.BtnCompute.MoveTo("46;16");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainWindow.BtnCompute' at 54;8.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(3));
            repo.MainWindow.BtnCompute.MoveTo("54;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.PnlUserControlCollection.TabErrRates' at 1222;663.", repo.MainWindow.PnlUserControlCollection.TabErrRatesInfo, new RecordItemIndex(4));
            repo.MainWindow.PnlUserControlCollection.TabErrRates.MoveTo("1222;663");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
