///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputtheparametersAndValidatePowerAndmodifiedPower recording.
    /// </summary>
    [TestModule("f7896ea8-9d4e-41cd-9075-048e1a3cb061", ModuleType.Recording, 1)]
    public partial class InputtheparametersAndValidatePowerAndmodifiedPower : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static InputtheparametersAndValidatePowerAndmodifiedPower instance = new InputtheparametersAndValidatePowerAndmodifiedPower();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputtheparametersAndValidatePowerAndmodifiedPower()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputtheparametersAndValidatePowerAndmodifiedPower Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.RdbOutputPower' at 7;7.", repo.MainWindow.PnlUserControlCollection.RdbOutputPowerInfo, new RecordItemIndex(0));
            repo.MainWindow.PnlUserControlCollection.RdbOutputPower.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(1));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '100' with focus on 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(2));
            repo.MainWindow.PnlCommonParameters.TxtSampleSize.PressKeys("100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(3));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(4));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.3' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(5));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(6));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.323') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.323");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(8));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.303') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.303");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC04_01
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(13));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(14));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(15));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(16));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.RdbOutputPower' at 7;7.", repo.MainWindow.PnlUserControlCollection.RdbOutputPowerInfo, new RecordItemIndex(17));
            repo.MainWindow.PnlUserControlCollection.RdbOutputPower.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.05' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(18));
            repo.MainWindow.TxtTypeIError.PressKeys("0.05");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '200' with focus on 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(19));
            repo.MainWindow.PnlCommonParameters.TxtSampleSize.PressKeys("200");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(20));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(21));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.1' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(22));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(23));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.174') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.174");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(25));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.154') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.154");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC04_02
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(30));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(31));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(32));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(33));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.RdbOutputPower' at 7;7.", repo.MainWindow.PnlUserControlCollection.RdbOutputPowerInfo, new RecordItemIndex(34));
            repo.MainWindow.PnlUserControlCollection.RdbOutputPower.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.05' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(35));
            repo.MainWindow.TxtTypeIError.PressKeys("0.05");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '250' with focus on 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(36));
            repo.MainWindow.PnlCommonParameters.TxtSampleSize.PressKeys("250");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(37));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(38));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.5' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(39));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys("0.5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(40));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.989') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.989");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(42));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(43));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.969') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.969");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(45));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC04_03
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(46));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(47));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(48));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(49));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(50));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.RdbOutputPower' at 7;7.", repo.MainWindow.PnlUserControlCollection.RdbOutputPowerInfo, new RecordItemIndex(51));
            repo.MainWindow.PnlUserControlCollection.RdbOutputPower.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(52));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '400' with focus on 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(53));
            repo.MainWindow.PnlCommonParameters.TxtSampleSize.PressKeys("400");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(54));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(55));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.1' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(56));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys("0.1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(57));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.168') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(58));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.168");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(59));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(60));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.148') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(61));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.148");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(62));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC04_04
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(64));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(65));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(66));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(67));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.RdbOutputPower' at 7;7.", repo.MainWindow.PnlUserControlCollection.RdbOutputPowerInfo, new RecordItemIndex(68));
            repo.MainWindow.PnlUserControlCollection.RdbOutputPower.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(69));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '500' with focus on 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(70));
            repo.MainWindow.PnlCommonParameters.TxtSampleSize.PressKeys("500");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(71));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(72));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.3' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(73));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys("0.3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(74));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.940') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(75));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.940");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(76));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(77));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.920') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(78));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.920");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(79));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC04_05
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(80));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(81));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
