///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputMethodIndividualmeans recording.
    /// </summary>
    [TestModule("feea4e50-8474-44ec-a4a9-4b3aa6bf30a6", ModuleType.Recording, 1)]
    public partial class InputMethodIndividualmeans : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static InputMethodIndividualmeans instance = new InputMethodIndividualmeans();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputMethodIndividualmeans()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputMethodIndividualmeans Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>&Input Method:</n>') on item 'MainWindow.PnlUserControlCollection.LblInputMethod'.", repo.MainWindow.PnlUserControlCollection.LblInputMethodInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.LblInputMethodInfo, "Text", "<n>&Input Method:</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Individual Means') on item 'MainWindow.PnlUserControlCollection.CmbInputMethod'.", repo.MainWindow.PnlUserControlCollection.CmbInputMethodInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.CmbInputMethodInfo, "Text", "Individual Means");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedItem='Individual Means') on item 'MainWindow.PnlUserControlCollection.CmbInputMethod'.", repo.MainWindow.PnlUserControlCollection.CmbInputMethodInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.CmbInputMethodInfo, "SelectedItem", "Individual Means");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
