///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputtheparametersFortheTest recording.
    /// </summary>
    [TestModule("634390ac-675f-4225-89ca-dc8a168b1266", ModuleType.Recording, 1)]
    public partial class InputtheparametersFortheTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static InputtheparametersFortheTest instance = new InputtheparametersFortheTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputtheparametersFortheTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputtheparametersFortheTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(0));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(1));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.3' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(2));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(3));
            repo.MainWindow.PnlUserControlCollection.TxtSigma.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.7' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(4));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(5));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(6));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(7));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='275') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "Text", "275");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.68') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.68");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC05_01
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(13));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(14));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(15));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(16));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(17));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(18));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.1' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(19));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(20));
            repo.MainWindow.PnlUserControlCollection.TxtSigma.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.7' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(21));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(22));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(23));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.7') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.7");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(25));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2469') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "Text", "2469");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.68') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.68");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC05_02
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(31));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(32));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(33));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(34));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(35));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(36));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.3' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(37));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(38));
            repo.MainWindow.PnlUserControlCollection.TxtSigma.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.9' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(39));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(40));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(41));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.9') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(42));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.9");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(43));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='467') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "Text", "467");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(45));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.88') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.88");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(47));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC05_03
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(48));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(49));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(50));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(51));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(52));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0.025' with focus on 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(53));
            repo.MainWindow.TxtTypeIError.PressKeys("0.025");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(54));
            repo.MainWindow.PnlUserControlCollection.TxtMeanControl.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.5' with focus on 'MainWindow.PnlUserControlCollection.TxtMeanTRMTSup'.", repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSupInfo, new RecordItemIndex(55));
            repo.MainWindow.PnlUserControlCollection.TxtMeanTRMTSup.PressKeys(".5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(56));
            repo.MainWindow.PnlUserControlCollection.TxtSigma.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.9' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(57));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.PnlCommonParameters.TxtAllocationRatio'.", repo.MainWindow.PnlCommonParameters.TxtAllocationRatioInfo, new RecordItemIndex(58));
            repo.MainWindow.PnlCommonParameters.TxtAllocationRatio.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.BtnCompute' at 44;19.", repo.MainWindow.BtnComputeInfo, new RecordItemIndex(59));
            repo.MainWindow.BtnCompute.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.9') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(60));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", "0.9");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(61));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='169') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(62));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "Text", "169");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlCommonParameters.TxtSampleSize'.", repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, new RecordItemIndex(63));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtSampleSizeInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.88') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(64));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "Text", "0.88");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='255, 255, 153') on item 'MainWindow.PnlUserControlCollection.TxtModifiedPower'.", repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, new RecordItemIndex(65));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtModifiedPowerInfo, "BackColor", "255, 255, 153");
            Delay.Milliseconds(100);
            
            // TC05_04
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(66));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Close' at 6;14.", repo.MainWindow.CloseInfo, new RecordItemIndex(67));
            repo.MainWindow.Close.Click("6;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
