///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchtheEastapplication recording.
    /// </summary>
    [TestModule("4e25e16d-666e-422f-9fc5-0c5d282d3822", ModuleType.Recording, 1)]
    public partial class LaunchtheEastapplication : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static LaunchtheEastapplication instance = new LaunchtheEastapplication();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchtheEastapplication()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchtheEastapplication Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Administrator\\Desktop\\EastSunrisers\\US-ES-3(Iteration Branch)_IndependentTesting\\Cytel.Architect2011.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Administrator\\Desktop\\EastSunrisers\\US-ES-3(Iteration Branch)_IndependentTesting\\Cytel.Architect2011.exe", "", "C:\\Users\\Administrator\\Desktop\\EastSunrisers\\US-ES-3(Iteration Branch)_IndependentTesting", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeDialog.BtnOK' at 33;7.", repo.WelcomeDialog.BtnOKInfo, new RecordItemIndex(2));
            //repo.WelcomeDialog.BtnOK.Click("33;7");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeDialog.BtnCancel' at 55;14.", repo.WelcomeDialog.BtnCancelInfo, new RecordItemIndex(3));
            repo.WelcomeDialog.BtnCancel.Click("55;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.TxtLog' at 1;36.", repo.MainWindow.TxtLogInfo, new RecordItemIndex(4));
            repo.MainWindow.TxtLog.MoveTo("1;36");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.TxtLog' at 257;25.", repo.MainWindow.TxtLogInfo, new RecordItemIndex(5));
            repo.MainWindow.TxtLog.MoveTo("257;25");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedText='Wednesday, January 23, 2019') on item 'MainWindow.TxtLog'.", repo.MainWindow.TxtLogInfo, new RecordItemIndex(6));
            //Validate.AttributeEqual(repo.MainWindow.TxtLogInfo, "SelectedText", "Wednesday, January 23, 2019");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.MasterRanorexStudioAdministrator' at 33;36.", repo.Explorer.MasterRanorexStudioAdministratorInfo, new RecordItemIndex(7));
            repo.Explorer.MasterRanorexStudioAdministrator.Click("33;36");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
