///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MasterRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("d3a2ae6a-0cc6-4dc4-a51c-e1c347719e71")]
    public partial class MasterRepository : RepoGenBaseFolder
    {
        static MasterRepository instance = new MasterRepository();
        MasterRepositoryFolders.WelcomeDialogAppFolder _welcomedialog;
        MasterRepositoryFolders.MainWindowAppFolder _mainwindow;
        MasterRepositoryFolders.ExplorerAppFolder _explorer;
        MasterRepositoryFolders.CytelArchitect2011AppFolder _cytelarchitect2011;
        MasterRepositoryFolders.MyDocumentsAppFolder _mydocuments;
        MasterRepositoryFolders.Explorer1AppFolder _explorer1;
        MasterRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the MasterRepository element repository.
        /// </summary>
        [RepositoryFolder("d3a2ae6a-0cc6-4dc4-a51c-e1c347719e71")]
        public static MasterRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MasterRepository() 
            : base("MasterRepository", "/", null, 0, false, "d3a2ae6a-0cc6-4dc4-a51c-e1c347719e71", ".\\RepositoryImages\\MasterRepositoryd3a2ae6a.rximgres")
        {
            _welcomedialog = new MasterRepositoryFolders.WelcomeDialogAppFolder(this);
            _mainwindow = new MasterRepositoryFolders.MainWindowAppFolder(this);
            _explorer = new MasterRepositoryFolders.ExplorerAppFolder(this);
            _cytelarchitect2011 = new MasterRepositoryFolders.CytelArchitect2011AppFolder(this);
            _mydocuments = new MasterRepositoryFolders.MyDocumentsAppFolder(this);
            _explorer1 = new MasterRepositoryFolders.Explorer1AppFolder(this);
            _list1000 = new MasterRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d3a2ae6a-0cc6-4dc4-a51c-e1c347719e71")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WelcomeDialog folder.
        /// </summary>
        [RepositoryFolder("6f6205c0-6eac-4918-a0f9-034b94f2751f")]
        public virtual MasterRepositoryFolders.WelcomeDialogAppFolder WelcomeDialog
        {
            get { return _welcomedialog; }
        }

        /// <summary>
        /// The MainWindow folder.
        /// </summary>
        [RepositoryFolder("15102e12-8654-4b34-aad6-6755182e9d26")]
        public virtual MasterRepositoryFolders.MainWindowAppFolder MainWindow
        {
            get { return _mainwindow; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("afe5b183-7073-4720-8d69-63a41fc571b9")]
        public virtual MasterRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The CytelArchitect2011 folder.
        /// </summary>
        [RepositoryFolder("9fd8e872-75b5-4d02-a6d6-2a4d5dee1252")]
        public virtual MasterRepositoryFolders.CytelArchitect2011AppFolder CytelArchitect2011
        {
            get { return _cytelarchitect2011; }
        }

        /// <summary>
        /// The MyDocuments folder.
        /// </summary>
        [RepositoryFolder("417467a6-b09d-421c-b086-340283711257")]
        public virtual MasterRepositoryFolders.MyDocumentsAppFolder MyDocuments
        {
            get { return _mydocuments; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("b551d97e-16bb-4b1d-bfd0-e0d7c4a9fff6")]
        public virtual MasterRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("856aefe8-c82b-4e3e-aaa6-e108648c410f")]
        public virtual MasterRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MasterRepositoryFolders
    {
        /// <summary>
        /// The WelcomeDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("6f6205c0-6eac-4918-a0f9-034b94f2751f")]
        public partial class WelcomeDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnokInfo;
            RepoItemInfo _btncancelInfo;

            /// <summary>
            /// Creates a new WelcomeDialog  folder.
            /// </summary>
            public WelcomeDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeDialog", "/form[@controlname='WelcomeDialog']", parentFolder, 30000, null, true, "6f6205c0-6eac-4918-a0f9-034b94f2751f", "")
            {
                _btnokInfo = new RepoItemInfo(this, "BtnOK", "button[@controlname='btnOK']", 30000, null, "c74f1029-ab18-43fe-b582-734c52885b06");
                _btncancelInfo = new RepoItemInfo(this, "BtnCancel", "button[@controlname='btnCancel']", 30000, null, "3400c8fa-0df9-4f56-8f60-9f2d91c812a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6f6205c0-6eac-4918-a0f9-034b94f2751f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6f6205c0-6eac-4918-a0f9-034b94f2751f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnOK item.
            /// </summary>
            [RepositoryItem("c74f1029-ab18-43fe-b582-734c52885b06")]
            public virtual Ranorex.Button BtnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnOK item info.
            /// </summary>
            [RepositoryItemInfo("c74f1029-ab18-43fe-b582-734c52885b06")]
            public virtual RepoItemInfo BtnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The BtnCancel item.
            /// </summary>
            [RepositoryItem("3400c8fa-0df9-4f56-8f60-9f2d91c812a8")]
            public virtual Ranorex.Button BtnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnCancel item info.
            /// </summary>
            [RepositoryItemInfo("3400c8fa-0df9-4f56-8f60-9f2d91c812a8")]
            public virtual RepoItemInfo BtnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }
        }

        /// <summary>
        /// The MainWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("15102e12-8654-4b34-aad6-6755182e9d26")]
        public partial class MainWindowAppFolder : RepoGenBaseFolder
        {
            MasterRepositoryFolders.PnlCommonParametersFolder _pnlcommonparameters;
            MasterRepositoryFolders.PnlUserControlCollectionFolder _pnlusercontrolcollection;
            RepoItemInfo _txtlogInfo;
            RepoItemInfo _twosamplesInfo;
            RepoItemInfo _groupingInfo;
            RepoItemInfo _continuousInfo;
            RepoItemInfo _designcontinuousendpointtwosampleInfo;
            RepoItemInfo _lbltypeierrorInfo;
            RepoItemInfo _txttypeierrorInfo;
            RepoItemInfo _lbltrialtypeInfo;
            RepoItemInfo _cmbtrialtypeInfo;
            RepoItemInfo _btncomputeInfo;
            RepoItemInfo _dotnetbarbarInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _cmblooksInfo;

            /// <summary>
            /// Creates a new MainWindow  folder.
            /// </summary>
            public MainWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainWindow", "/form[@controlname='MainWindow']", parentFolder, 30000, null, true, "15102e12-8654-4b34-aad6-6755182e9d26", "")
            {
                _pnlcommonparameters = new MasterRepositoryFolders.PnlCommonParametersFolder(this);
                _pnlusercontrolcollection = new MasterRepositoryFolders.PnlUserControlCollectionFolder(this);
                _txtlogInfo = new RepoItemInfo(this, "TxtLog", "?/?/form[@controlname='ChildWindow']/container[@controlname='UcLog']/?/?/text[@controlname='txtLog']", 30000, null, "75e7c701-dad7-42f5-87c3-2e9c4cfe120f");
                _twosamplesInfo = new RepoItemInfo(this, "TwoSamples", "container[@controlname='rbnctrlArchitect']/?/?/container[@controlname='rbnBarEastContinuous']//button[@accessiblename='Two Samples']", 30000, null, "6b4e417b-4bbe-4fdd-b32c-ffd61d40a834");
                _groupingInfo = new RepoItemInfo(this, "Grouping", "container[@controlname='rbnctrlArchitect']/container[@controlname='ඇ']/element[@accessiblerole='Default']/container[1]", 30000, null, "c116a7e1-00a7-489c-967f-db3e40ffeff6");
                _continuousInfo = new RepoItemInfo(this, "Continuous", "container[@controlname='rbnctrlArchitect']//element[@accessiblename='Continuous']", 30000, null, "17ff5a02-8d0a-48db-bd0c-269c6aaae0f2");
                _designcontinuousendpointtwosampleInfo = new RepoItemInfo(this, "DesignContinuousEndpointTwoSample", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//toolbar[@accessiblename='bar1']/element[@accessiblename~'^Design:\\ Continuous\\ Endpoi']", 30000, null, "325a5923-69a0-40c0-8ddf-3ad57fa3273a");
                _lbltypeierrorInfo = new RepoItemInfo(this, "LblTypeIError", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlUserControlCollection']//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/container[@controlname='pnlSymmetricAlpha']/text[@controlname='lblTypeIError']", 30000, null, "1ffb64b8-5a86-43a8-b360-d767c9f5cf23");
                _txttypeierrorInfo = new RepoItemInfo(this, "TxtTypeIError", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlUserControlCollection']//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/container[@controlname='pnlSymmetricAlpha']/text[@controlname='txtTypeIError']", 30000, null, "1140f454-9080-4013-904d-b7d773f2bf1a");
                _lbltrialtypeInfo = new RepoItemInfo(this, "LblTrialType", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlCommonControls']/text[@controlname='lblTrialType']", 30000, null, "14f23221-b1bf-43b8-9c07-15ada4053889");
                _cmbtrialtypeInfo = new RepoItemInfo(this, "CmbTrialType", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlCommonControls']/combobox[@controlname='cmbTrialType']", 30000, null, "e3515fc1-ecac-41d1-8eb5-35363ca51cbd");
                _btncomputeInfo = new RepoItemInfo(this, "BtnCompute", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlButtonCollection']/button[@controlname='btnCompute']", 30000, null, "da5cf6d8-7c9d-45a9-bae1-041ee9cbf039");
                _dotnetbarbarInfo = new RepoItemInfo(this, "DotNetBarBar", "?/?/statusbar[@accessiblename='DotNetBar Bar']", 30000, null, "43dbe81c-30ec-489e-966d-1bc1bfd968c7");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/form[@controlname='DesignChildWindow']/?/?/button[@accessiblename='Close']", 30000, null, "c820b843-ef23-45b1-9233-6376845017f7");
                _openInfo = new RepoItemInfo(this, "Open", "?/?/form[@controlname='DesignChildWindow']/?/?/container[@controlname='panelDesign']//container[@controlname='pnlCommonControls']/combobox[@controlname='cmbTrialType']/button[@accessiblename='Open']", 30000, null, "b8b613d2-819c-436c-a366-61f0c6ad6247");
                _cmblooksInfo = new RepoItemInfo(this, "CmbLooks", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']/container[@controlname='panelDesign']//container[@controlname='pnlCommonControls']/combobox[@controlname='cmbLooks']", 30000, null, "7a3f5421-aab4-4f21-b6dd-509c814647da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("15102e12-8654-4b34-aad6-6755182e9d26")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("15102e12-8654-4b34-aad6-6755182e9d26")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtLog item.
            /// </summary>
            [RepositoryItem("75e7c701-dad7-42f5-87c3-2e9c4cfe120f")]
            public virtual Ranorex.Text TxtLog
            {
                get
                {
                    return _txtlogInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLog item info.
            /// </summary>
            [RepositoryItemInfo("75e7c701-dad7-42f5-87c3-2e9c4cfe120f")]
            public virtual RepoItemInfo TxtLogInfo
            {
                get
                {
                    return _txtlogInfo;
                }
            }

            /// <summary>
            /// The TwoSamples item.
            /// </summary>
            [RepositoryItem("6b4e417b-4bbe-4fdd-b32c-ffd61d40a834")]
            public virtual Ranorex.Button TwoSamples
            {
                get
                {
                    return _twosamplesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TwoSamples item info.
            /// </summary>
            [RepositoryItemInfo("6b4e417b-4bbe-4fdd-b32c-ffd61d40a834")]
            public virtual RepoItemInfo TwoSamplesInfo
            {
                get
                {
                    return _twosamplesInfo;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("c116a7e1-00a7-489c-967f-db3e40ffeff6")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("c116a7e1-00a7-489c-967f-db3e40ffeff6")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }

            /// <summary>
            /// The Continuous item.
            /// </summary>
            [RepositoryItem("17ff5a02-8d0a-48db-bd0c-269c6aaae0f2")]
            public virtual Ranorex.Unknown Continuous
            {
                get
                {
                    return _continuousInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Continuous item info.
            /// </summary>
            [RepositoryItemInfo("17ff5a02-8d0a-48db-bd0c-269c6aaae0f2")]
            public virtual RepoItemInfo ContinuousInfo
            {
                get
                {
                    return _continuousInfo;
                }
            }

            /// <summary>
            /// The DesignContinuousEndpointTwoSample item.
            /// </summary>
            [RepositoryItem("325a5923-69a0-40c0-8ddf-3ad57fa3273a")]
            public virtual Ranorex.Unknown DesignContinuousEndpointTwoSample
            {
                get
                {
                    return _designcontinuousendpointtwosampleInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DesignContinuousEndpointTwoSample item info.
            /// </summary>
            [RepositoryItemInfo("325a5923-69a0-40c0-8ddf-3ad57fa3273a")]
            public virtual RepoItemInfo DesignContinuousEndpointTwoSampleInfo
            {
                get
                {
                    return _designcontinuousendpointtwosampleInfo;
                }
            }

            /// <summary>
            /// The LblTypeIError item.
            /// </summary>
            [RepositoryItem("1ffb64b8-5a86-43a8-b360-d767c9f5cf23")]
            public virtual Ranorex.Text LblTypeIError
            {
                get
                {
                    return _lbltypeierrorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblTypeIError item info.
            /// </summary>
            [RepositoryItemInfo("1ffb64b8-5a86-43a8-b360-d767c9f5cf23")]
            public virtual RepoItemInfo LblTypeIErrorInfo
            {
                get
                {
                    return _lbltypeierrorInfo;
                }
            }

            /// <summary>
            /// The TxtTypeIError item.
            /// </summary>
            [RepositoryItem("1140f454-9080-4013-904d-b7d773f2bf1a")]
            public virtual Ranorex.Text TxtTypeIError
            {
                get
                {
                    return _txttypeierrorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtTypeIError item info.
            /// </summary>
            [RepositoryItemInfo("1140f454-9080-4013-904d-b7d773f2bf1a")]
            public virtual RepoItemInfo TxtTypeIErrorInfo
            {
                get
                {
                    return _txttypeierrorInfo;
                }
            }

            /// <summary>
            /// The LblTrialType item.
            /// </summary>
            [RepositoryItem("14f23221-b1bf-43b8-9c07-15ada4053889")]
            public virtual Ranorex.Text LblTrialType
            {
                get
                {
                    return _lbltrialtypeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblTrialType item info.
            /// </summary>
            [RepositoryItemInfo("14f23221-b1bf-43b8-9c07-15ada4053889")]
            public virtual RepoItemInfo LblTrialTypeInfo
            {
                get
                {
                    return _lbltrialtypeInfo;
                }
            }

            /// <summary>
            /// The CmbTrialType item.
            /// </summary>
            [RepositoryItem("e3515fc1-ecac-41d1-8eb5-35363ca51cbd")]
            public virtual Ranorex.ComboBox CmbTrialType
            {
                get
                {
                    return _cmbtrialtypeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbTrialType item info.
            /// </summary>
            [RepositoryItemInfo("e3515fc1-ecac-41d1-8eb5-35363ca51cbd")]
            public virtual RepoItemInfo CmbTrialTypeInfo
            {
                get
                {
                    return _cmbtrialtypeInfo;
                }
            }

            /// <summary>
            /// The BtnCompute item.
            /// </summary>
            [RepositoryItem("da5cf6d8-7c9d-45a9-bae1-041ee9cbf039")]
            public virtual Ranorex.Button BtnCompute
            {
                get
                {
                    return _btncomputeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnCompute item info.
            /// </summary>
            [RepositoryItemInfo("da5cf6d8-7c9d-45a9-bae1-041ee9cbf039")]
            public virtual RepoItemInfo BtnComputeInfo
            {
                get
                {
                    return _btncomputeInfo;
                }
            }

            /// <summary>
            /// The DotNetBarBar item.
            /// </summary>
            [RepositoryItem("43dbe81c-30ec-489e-966d-1bc1bfd968c7")]
            public virtual Ranorex.StatusBar DotNetBarBar
            {
                get
                {
                    return _dotnetbarbarInfo.CreateAdapter<Ranorex.StatusBar>(true);
                }
            }

            /// <summary>
            /// The DotNetBarBar item info.
            /// </summary>
            [RepositoryItemInfo("43dbe81c-30ec-489e-966d-1bc1bfd968c7")]
            public virtual RepoItemInfo DotNetBarBarInfo
            {
                get
                {
                    return _dotnetbarbarInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("c820b843-ef23-45b1-9233-6376845017f7")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("c820b843-ef23-45b1-9233-6376845017f7")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("b8b613d2-819c-436c-a366-61f0c6ad6247")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("b8b613d2-819c-436c-a366-61f0c6ad6247")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The CmbLooks item.
            /// </summary>
            [RepositoryItem("7a3f5421-aab4-4f21-b6dd-509c814647da")]
            public virtual Ranorex.ComboBox CmbLooks
            {
                get
                {
                    return _cmblooksInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbLooks item info.
            /// </summary>
            [RepositoryItemInfo("7a3f5421-aab4-4f21-b6dd-509c814647da")]
            public virtual RepoItemInfo CmbLooksInfo
            {
                get
                {
                    return _cmblooksInfo;
                }
            }

            /// <summary>
            /// The PnlCommonParameters folder.
            /// </summary>
            [RepositoryFolder("561a9b1c-c022-4783-bd03-0fbd12b0ca3a")]
            public virtual MasterRepositoryFolders.PnlCommonParametersFolder PnlCommonParameters
            {
                get { return _pnlcommonparameters; }
            }

            /// <summary>
            /// The PnlUserControlCollection folder.
            /// </summary>
            [RepositoryFolder("e6dff44b-463e-4677-a740-70ce8d8556b4")]
            public virtual MasterRepositoryFolders.PnlUserControlCollectionFolder PnlUserControlCollection
            {
                get { return _pnlusercontrolcollection; }
            }
        }

        /// <summary>
        /// The PnlCommonParametersFolder folder.
        /// </summary>
        [RepositoryFolder("561a9b1c-c022-4783-bd03-0fbd12b0ca3a")]
        public partial class PnlCommonParametersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblallocationratioInfo;
            RepoItemInfo _lblallocationratioformulaInfo;
            RepoItemInfo _lblpowerInfo;
            RepoItemInfo _lblsamplesizeInfo;
            RepoItemInfo _txtallocationratioInfo;
            RepoItemInfo _txtpowerInfo;
            RepoItemInfo _txtsamplesizeInfo;

            /// <summary>
            /// Creates a new PnlCommonParameters  folder.
            /// </summary>
            public PnlCommonParametersFolder(RepoGenBaseFolder parentFolder) :
                    base("PnlCommonParameters", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlUserControlCollection']//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/container[@controlname='pnlCommonParameters']", parentFolder, 30000, null, false, "561a9b1c-c022-4783-bd03-0fbd12b0ca3a", "")
            {
                _lblallocationratioInfo = new RepoItemInfo(this, "LblAllocationRatio", "text[@controlname='lblAllocationRatio']", 30000, null, "65d6c52c-594e-496c-851f-9a2c99acbef7");
                _lblallocationratioformulaInfo = new RepoItemInfo(this, "LblAllocationRatioformula", "text[@controlname='lblAllocationRatioformula']", 30000, null, "389b7ce9-e416-49e4-864b-81b946a81260");
                _lblpowerInfo = new RepoItemInfo(this, "LblPower", "text[@controlname='lblPower']", 30000, null, "42d9cc1a-da80-44e2-8be7-78e48daa5810");
                _lblsamplesizeInfo = new RepoItemInfo(this, "LblSampleSize", "text[@controlname='lblSampleSize']", 30000, null, "6d336b0c-ad66-43ac-8ecc-49bade3fbb28");
                _txtallocationratioInfo = new RepoItemInfo(this, "TxtAllocationRatio", "text[@controlname='txtAllocationRatio']", 30000, null, "15e483a8-e861-48fc-990f-e0ea09a79595");
                _txtpowerInfo = new RepoItemInfo(this, "TxtPower", "text[@controlname='txtPower']", 30000, null, "904b11c3-611b-4bf3-86b4-238853077945");
                _txtsamplesizeInfo = new RepoItemInfo(this, "TxtSampleSize", "text[@controlname='txtSampleSize']", 30000, null, "fa55cd16-f132-4435-9277-2af4735d55a5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("561a9b1c-c022-4783-bd03-0fbd12b0ca3a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("561a9b1c-c022-4783-bd03-0fbd12b0ca3a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblAllocationRatio item.
            /// </summary>
            [RepositoryItem("65d6c52c-594e-496c-851f-9a2c99acbef7")]
            public virtual Ranorex.Text LblAllocationRatio
            {
                get
                {
                    return _lblallocationratioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblAllocationRatio item info.
            /// </summary>
            [RepositoryItemInfo("65d6c52c-594e-496c-851f-9a2c99acbef7")]
            public virtual RepoItemInfo LblAllocationRatioInfo
            {
                get
                {
                    return _lblallocationratioInfo;
                }
            }

            /// <summary>
            /// The LblAllocationRatioformula item.
            /// </summary>
            [RepositoryItem("389b7ce9-e416-49e4-864b-81b946a81260")]
            public virtual Ranorex.Text LblAllocationRatioformula
            {
                get
                {
                    return _lblallocationratioformulaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblAllocationRatioformula item info.
            /// </summary>
            [RepositoryItemInfo("389b7ce9-e416-49e4-864b-81b946a81260")]
            public virtual RepoItemInfo LblAllocationRatioformulaInfo
            {
                get
                {
                    return _lblallocationratioformulaInfo;
                }
            }

            /// <summary>
            /// The LblPower item.
            /// </summary>
            [RepositoryItem("42d9cc1a-da80-44e2-8be7-78e48daa5810")]
            public virtual Ranorex.Text LblPower
            {
                get
                {
                    return _lblpowerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblPower item info.
            /// </summary>
            [RepositoryItemInfo("42d9cc1a-da80-44e2-8be7-78e48daa5810")]
            public virtual RepoItemInfo LblPowerInfo
            {
                get
                {
                    return _lblpowerInfo;
                }
            }

            /// <summary>
            /// The LblSampleSize item.
            /// </summary>
            [RepositoryItem("6d336b0c-ad66-43ac-8ecc-49bade3fbb28")]
            public virtual Ranorex.Text LblSampleSize
            {
                get
                {
                    return _lblsamplesizeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblSampleSize item info.
            /// </summary>
            [RepositoryItemInfo("6d336b0c-ad66-43ac-8ecc-49bade3fbb28")]
            public virtual RepoItemInfo LblSampleSizeInfo
            {
                get
                {
                    return _lblsamplesizeInfo;
                }
            }

            /// <summary>
            /// The TxtAllocationRatio item.
            /// </summary>
            [RepositoryItem("15e483a8-e861-48fc-990f-e0ea09a79595")]
            public virtual Ranorex.Text TxtAllocationRatio
            {
                get
                {
                    return _txtallocationratioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtAllocationRatio item info.
            /// </summary>
            [RepositoryItemInfo("15e483a8-e861-48fc-990f-e0ea09a79595")]
            public virtual RepoItemInfo TxtAllocationRatioInfo
            {
                get
                {
                    return _txtallocationratioInfo;
                }
            }

            /// <summary>
            /// The TxtPower item.
            /// </summary>
            [RepositoryItem("904b11c3-611b-4bf3-86b4-238853077945")]
            public virtual Ranorex.Text TxtPower
            {
                get
                {
                    return _txtpowerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtPower item info.
            /// </summary>
            [RepositoryItemInfo("904b11c3-611b-4bf3-86b4-238853077945")]
            public virtual RepoItemInfo TxtPowerInfo
            {
                get
                {
                    return _txtpowerInfo;
                }
            }

            /// <summary>
            /// The TxtSampleSize item.
            /// </summary>
            [RepositoryItem("fa55cd16-f132-4435-9277-2af4735d55a5")]
            public virtual Ranorex.Text TxtSampleSize
            {
                get
                {
                    return _txtsamplesizeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtSampleSize item info.
            /// </summary>
            [RepositoryItemInfo("fa55cd16-f132-4435-9277-2af4735d55a5")]
            public virtual RepoItemInfo TxtSampleSizeInfo
            {
                get
                {
                    return _txtsamplesizeInfo;
                }
            }
        }

        /// <summary>
        /// The PnlUserControlCollectionFolder folder.
        /// </summary>
        [RepositoryFolder("e6dff44b-463e-4677-a740-70ce8d8556b4")]
        public partial class PnlUserControlCollectionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rdboutputpowerInfo;
            RepoItemInfo _rdboutputssInfo;
            RepoItemInfo _taberrratesInfo;
            RepoItemInfo _lblsamplesizeInfo;
            RepoItemInfo _lblmodifiedpowerInfo;
            RepoItemInfo _lblmeancontrolInfo;
            RepoItemInfo _txtmeancontrolInfo;
            RepoItemInfo _lblstddeviationInfo;
            RepoItemInfo _txtsigmaInfo;
            RepoItemInfo _lblinputmethodInfo;
            RepoItemInfo _cmbinputmethodInfo;
            RepoItemInfo _lblteststatInfo;
            RepoItemInfo _cmbteststatInfo;
            RepoItemInfo _lblsidetypeInfo;
            RepoItemInfo _cmbsidetypeInfo;
            RepoItemInfo _txtmodifiedpowerInfo;
            RepoItemInfo _pnlsymmetricalphaInfo;
            RepoItemInfo _txtmeantrmtsupInfo;
            RepoItemInfo _testparametersInfo;
            RepoItemInfo _pnlcommonparametersInfo;
            RepoItemInfo _commoncontainerdesigncontaineruccommonInfo;

            /// <summary>
            /// Creates a new PnlUserControlCollection  folder.
            /// </summary>
            public PnlUserControlCollectionFolder(RepoGenBaseFolder parentFolder) :
                    base("PnlUserControlCollection", "?/?/form[@controlname='DesignChildWindow']/container[@controlname='panel1']//container[@controlname='commonContainer']/?/?/container[@controlname='pnlUserControlCollection']", parentFolder, 30000, null, false, "e6dff44b-463e-4677-a740-70ce8d8556b4", "")
            {
                _rdboutputpowerInfo = new RepoItemInfo(this, "RdbOutputPower", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/radiobutton[@controlname='rdbOutputPower']", 30000, null, "538361a8-902e-4f4e-b836-93787ff87856");
                _rdboutputssInfo = new RepoItemInfo(this, "RdbOutputSS", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/radiobutton[@controlname='rdbOutputSS']", 30000, null, "fa684cb9-bb3c-4181-af01-3a15fc09ec50");
                _taberrratesInfo = new RepoItemInfo(this, "TabErrRates", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']", 30000, null, "1ad66096-d63f-4c46-a03e-606c44e96c11");
                _lblsamplesizeInfo = new RepoItemInfo(this, "LblSampleSize", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabPageDesignParams']/?/?/container[@controlname='commonContainer_designUC_commonDesignParamsUC']/?/?/text[@controlname='lblSampleSize']", 30000, null, "01c6048a-5141-412d-9ecc-7e1b17aa722c");
                _lblmodifiedpowerInfo = new RepoItemInfo(this, "LblModifiedPower", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/text[@controlname='lblModifiedPower']", 30000, null, "b5eae596-695f-4d8a-9625-f674ad92e2bc");
                _lblmeancontrolInfo = new RepoItemInfo(this, "LblMeanControl", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/container[@controlname='tblPanelDiffOfMeans']/container[@controlname='grpMeanCtrl']/text[@controlname='lblMeanControl']", 30000, null, "6fc51374-a4e0-49d7-91e0-b63ec65ee39b");
                _txtmeancontrolInfo = new RepoItemInfo(this, "TxtMeanControl", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/container[@controlname='tblPanelDiffOfMeans']/container[@controlname='grpMeanCtrl']/text[@controlname='txtMeanControl']", 30000, null, "7800c6b9-807e-4383-912d-7d3648570de9");
                _lblstddeviationInfo = new RepoItemInfo(this, "LblStdDeviation", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/container[@controlname='grpStdDev']/text[@controlname='lblStdDeviation']", 30000, null, "1eb49918-6577-42a4-a3ec-5f6b65f24790");
                _txtsigmaInfo = new RepoItemInfo(this, "TxtSigma", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/container[@controlname='grpStdDev']/text[@controlname='txtSigma']", 30000, null, "882a0186-daec-43d9-a514-3cc5999479e3");
                _lblinputmethodInfo = new RepoItemInfo(this, "LblInputMethod", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/text[@controlname='lblInputMethod']", 30000, null, "d7c38a1f-855e-4e94-ba82-948b74037ac9");
                _cmbinputmethodInfo = new RepoItemInfo(this, "CmbInputMethod", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/combobox[@controlname='cmbInputMethod']", 30000, null, "3dac9cd8-ebdb-4566-9746-e7a7f0d12ab3");
                _lblteststatInfo = new RepoItemInfo(this, "LblTestStat", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/text[@controlname='lblTestStat']", 30000, null, "3ebf1f4d-6776-4a17-9ea8-5570246d7e86");
                _cmbteststatInfo = new RepoItemInfo(this, "CmbTestStat", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/combobox[@controlname='cmbTestStat']", 30000, null, "7e1ad004-2b4f-4e7d-9b2f-b463e5c1ae87");
                _lblsidetypeInfo = new RepoItemInfo(this, "LblSideType", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/text[@controlname='lblSideType']", 30000, null, "a8b7c1a3-5756-41cf-8362-faebea4712e7");
                _cmbsidetypeInfo = new RepoItemInfo(this, "CmbSideType", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/combobox[@controlname='cmbSideType']", 30000, null, "65977d15-da52-4809-839f-f22bbf15dfe0");
                _txtmodifiedpowerInfo = new RepoItemInfo(this, "TxtModifiedPower", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/text[@controlname='txtModifiedPower']", 30000, null, "98e01fdb-dc71-4b6e-be25-91455b75d898");
                _pnlsymmetricalphaInfo = new RepoItemInfo(this, "PnlSymmetricAlpha", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/container[@controlname='pnlSymmetricAlpha']", 30000, null, "a2175d25-da7a-4631-9189-d023a2bee60d");
                _txtmeantrmtsupInfo = new RepoItemInfo(this, "TxtMeanTRMTSup", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_endPointParamsUC']/?/?/container[@controlname='tblPanelDiffOfMeans']/container[@controlname='grpMeanCtrl']/text[@controlname='txtMeanTRMTSup']", 30000, null, "769302a3-17df-45f6-9011-1d667b6738f7");
                _testparametersInfo = new RepoItemInfo(this, "TestParameters", ".//tabpage[@accessiblename='Test Parameters       ']", 30000, null, "d52772ee-450f-47ec-ae48-a9589d9cd2fb");
                _pnlcommonparametersInfo = new RepoItemInfo(this, "PnlCommonParameters", ".//tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']/container[@controlname='pnlCommonParameters']", 30000, null, "82cc06ee-5867-4062-af27-4731414f4de6");
                _commoncontainerdesigncontaineruccommonInfo = new RepoItemInfo(this, "CommonContainerDesignContainerUCCommon", "?/?/tabpagelist[@controlname='tabDesignPanel']/tabpage[@controlname='tabErrRates']/?/?/container[@controlname='commonContainer_designContainerUC_commonDesignParam']", 30000, null, "9bdab4a0-b68c-462d-8a7a-ee3d0ccc0578");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6dff44b-463e-4677-a740-70ce8d8556b4")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6dff44b-463e-4677-a740-70ce8d8556b4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RdbOutputPower item.
            /// </summary>
            [RepositoryItem("538361a8-902e-4f4e-b836-93787ff87856")]
            public virtual Ranorex.RadioButton RdbOutputPower
            {
                get
                {
                    return _rdboutputpowerInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbOutputPower item info.
            /// </summary>
            [RepositoryItemInfo("538361a8-902e-4f4e-b836-93787ff87856")]
            public virtual RepoItemInfo RdbOutputPowerInfo
            {
                get
                {
                    return _rdboutputpowerInfo;
                }
            }

            /// <summary>
            /// The RdbOutputSS item.
            /// </summary>
            [RepositoryItem("fa684cb9-bb3c-4181-af01-3a15fc09ec50")]
            public virtual Ranorex.RadioButton RdbOutputSS
            {
                get
                {
                    return _rdboutputssInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbOutputSS item info.
            /// </summary>
            [RepositoryItemInfo("fa684cb9-bb3c-4181-af01-3a15fc09ec50")]
            public virtual RepoItemInfo RdbOutputSSInfo
            {
                get
                {
                    return _rdboutputssInfo;
                }
            }

            /// <summary>
            /// The TabErrRates item.
            /// </summary>
            [RepositoryItem("1ad66096-d63f-4c46-a03e-606c44e96c11")]
            public virtual Ranorex.TabPage TabErrRates
            {
                get
                {
                    return _taberrratesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabErrRates item info.
            /// </summary>
            [RepositoryItemInfo("1ad66096-d63f-4c46-a03e-606c44e96c11")]
            public virtual RepoItemInfo TabErrRatesInfo
            {
                get
                {
                    return _taberrratesInfo;
                }
            }

            /// <summary>
            /// The LblSampleSize item.
            /// </summary>
            [RepositoryItem("01c6048a-5141-412d-9ecc-7e1b17aa722c")]
            public virtual Ranorex.Text LblSampleSize
            {
                get
                {
                    return _lblsamplesizeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblSampleSize item info.
            /// </summary>
            [RepositoryItemInfo("01c6048a-5141-412d-9ecc-7e1b17aa722c")]
            public virtual RepoItemInfo LblSampleSizeInfo
            {
                get
                {
                    return _lblsamplesizeInfo;
                }
            }

            /// <summary>
            /// The LblModifiedPower item.
            /// </summary>
            [RepositoryItem("b5eae596-695f-4d8a-9625-f674ad92e2bc")]
            public virtual Ranorex.Text LblModifiedPower
            {
                get
                {
                    return _lblmodifiedpowerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblModifiedPower item info.
            /// </summary>
            [RepositoryItemInfo("b5eae596-695f-4d8a-9625-f674ad92e2bc")]
            public virtual RepoItemInfo LblModifiedPowerInfo
            {
                get
                {
                    return _lblmodifiedpowerInfo;
                }
            }

            /// <summary>
            /// The LblMeanControl item.
            /// </summary>
            [RepositoryItem("6fc51374-a4e0-49d7-91e0-b63ec65ee39b")]
            public virtual Ranorex.Text LblMeanControl
            {
                get
                {
                    return _lblmeancontrolInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblMeanControl item info.
            /// </summary>
            [RepositoryItemInfo("6fc51374-a4e0-49d7-91e0-b63ec65ee39b")]
            public virtual RepoItemInfo LblMeanControlInfo
            {
                get
                {
                    return _lblmeancontrolInfo;
                }
            }

            /// <summary>
            /// The TxtMeanControl item.
            /// </summary>
            [RepositoryItem("7800c6b9-807e-4383-912d-7d3648570de9")]
            public virtual Ranorex.Text TxtMeanControl
            {
                get
                {
                    return _txtmeancontrolInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtMeanControl item info.
            /// </summary>
            [RepositoryItemInfo("7800c6b9-807e-4383-912d-7d3648570de9")]
            public virtual RepoItemInfo TxtMeanControlInfo
            {
                get
                {
                    return _txtmeancontrolInfo;
                }
            }

            /// <summary>
            /// The LblStdDeviation item.
            /// </summary>
            [RepositoryItem("1eb49918-6577-42a4-a3ec-5f6b65f24790")]
            public virtual Ranorex.Text LblStdDeviation
            {
                get
                {
                    return _lblstddeviationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblStdDeviation item info.
            /// </summary>
            [RepositoryItemInfo("1eb49918-6577-42a4-a3ec-5f6b65f24790")]
            public virtual RepoItemInfo LblStdDeviationInfo
            {
                get
                {
                    return _lblstddeviationInfo;
                }
            }

            /// <summary>
            /// The TxtSigma item.
            /// </summary>
            [RepositoryItem("882a0186-daec-43d9-a514-3cc5999479e3")]
            public virtual Ranorex.Text TxtSigma
            {
                get
                {
                    return _txtsigmaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtSigma item info.
            /// </summary>
            [RepositoryItemInfo("882a0186-daec-43d9-a514-3cc5999479e3")]
            public virtual RepoItemInfo TxtSigmaInfo
            {
                get
                {
                    return _txtsigmaInfo;
                }
            }

            /// <summary>
            /// The LblInputMethod item.
            /// </summary>
            [RepositoryItem("d7c38a1f-855e-4e94-ba82-948b74037ac9")]
            public virtual Ranorex.Text LblInputMethod
            {
                get
                {
                    return _lblinputmethodInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblInputMethod item info.
            /// </summary>
            [RepositoryItemInfo("d7c38a1f-855e-4e94-ba82-948b74037ac9")]
            public virtual RepoItemInfo LblInputMethodInfo
            {
                get
                {
                    return _lblinputmethodInfo;
                }
            }

            /// <summary>
            /// The CmbInputMethod item.
            /// </summary>
            [RepositoryItem("3dac9cd8-ebdb-4566-9746-e7a7f0d12ab3")]
            public virtual Ranorex.ComboBox CmbInputMethod
            {
                get
                {
                    return _cmbinputmethodInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbInputMethod item info.
            /// </summary>
            [RepositoryItemInfo("3dac9cd8-ebdb-4566-9746-e7a7f0d12ab3")]
            public virtual RepoItemInfo CmbInputMethodInfo
            {
                get
                {
                    return _cmbinputmethodInfo;
                }
            }

            /// <summary>
            /// The LblTestStat item.
            /// </summary>
            [RepositoryItem("3ebf1f4d-6776-4a17-9ea8-5570246d7e86")]
            public virtual Ranorex.Text LblTestStat
            {
                get
                {
                    return _lblteststatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblTestStat item info.
            /// </summary>
            [RepositoryItemInfo("3ebf1f4d-6776-4a17-9ea8-5570246d7e86")]
            public virtual RepoItemInfo LblTestStatInfo
            {
                get
                {
                    return _lblteststatInfo;
                }
            }

            /// <summary>
            /// The CmbTestStat item.
            /// </summary>
            [RepositoryItem("7e1ad004-2b4f-4e7d-9b2f-b463e5c1ae87")]
            public virtual Ranorex.ComboBox CmbTestStat
            {
                get
                {
                    return _cmbteststatInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbTestStat item info.
            /// </summary>
            [RepositoryItemInfo("7e1ad004-2b4f-4e7d-9b2f-b463e5c1ae87")]
            public virtual RepoItemInfo CmbTestStatInfo
            {
                get
                {
                    return _cmbteststatInfo;
                }
            }

            /// <summary>
            /// The LblSideType item.
            /// </summary>
            [RepositoryItem("a8b7c1a3-5756-41cf-8362-faebea4712e7")]
            public virtual Ranorex.Text LblSideType
            {
                get
                {
                    return _lblsidetypeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblSideType item info.
            /// </summary>
            [RepositoryItemInfo("a8b7c1a3-5756-41cf-8362-faebea4712e7")]
            public virtual RepoItemInfo LblSideTypeInfo
            {
                get
                {
                    return _lblsidetypeInfo;
                }
            }

            /// <summary>
            /// The CmbSideType item.
            /// </summary>
            [RepositoryItem("65977d15-da52-4809-839f-f22bbf15dfe0")]
            public virtual Ranorex.ComboBox CmbSideType
            {
                get
                {
                    return _cmbsidetypeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbSideType item info.
            /// </summary>
            [RepositoryItemInfo("65977d15-da52-4809-839f-f22bbf15dfe0")]
            public virtual RepoItemInfo CmbSideTypeInfo
            {
                get
                {
                    return _cmbsidetypeInfo;
                }
            }

            /// <summary>
            /// The TxtModifiedPower item.
            /// </summary>
            [RepositoryItem("98e01fdb-dc71-4b6e-be25-91455b75d898")]
            public virtual Ranorex.Text TxtModifiedPower
            {
                get
                {
                    return _txtmodifiedpowerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtModifiedPower item info.
            /// </summary>
            [RepositoryItemInfo("98e01fdb-dc71-4b6e-be25-91455b75d898")]
            public virtual RepoItemInfo TxtModifiedPowerInfo
            {
                get
                {
                    return _txtmodifiedpowerInfo;
                }
            }

            /// <summary>
            /// The PnlSymmetricAlpha item.
            /// </summary>
            [RepositoryItem("a2175d25-da7a-4631-9189-d023a2bee60d")]
            public virtual Ranorex.Container PnlSymmetricAlpha
            {
                get
                {
                    return _pnlsymmetricalphaInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlSymmetricAlpha item info.
            /// </summary>
            [RepositoryItemInfo("a2175d25-da7a-4631-9189-d023a2bee60d")]
            public virtual RepoItemInfo PnlSymmetricAlphaInfo
            {
                get
                {
                    return _pnlsymmetricalphaInfo;
                }
            }

            /// <summary>
            /// The TxtMeanTRMTSup item.
            /// </summary>
            [RepositoryItem("769302a3-17df-45f6-9011-1d667b6738f7")]
            public virtual Ranorex.Text TxtMeanTRMTSup
            {
                get
                {
                    return _txtmeantrmtsupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtMeanTRMTSup item info.
            /// </summary>
            [RepositoryItemInfo("769302a3-17df-45f6-9011-1d667b6738f7")]
            public virtual RepoItemInfo TxtMeanTRMTSupInfo
            {
                get
                {
                    return _txtmeantrmtsupInfo;
                }
            }

            /// <summary>
            /// The TestParameters item.
            /// </summary>
            [RepositoryItem("d52772ee-450f-47ec-ae48-a9589d9cd2fb")]
            public virtual Ranorex.TabPage TestParameters
            {
                get
                {
                    return _testparametersInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestParameters item info.
            /// </summary>
            [RepositoryItemInfo("d52772ee-450f-47ec-ae48-a9589d9cd2fb")]
            public virtual RepoItemInfo TestParametersInfo
            {
                get
                {
                    return _testparametersInfo;
                }
            }

            /// <summary>
            /// The PnlCommonParameters item.
            /// </summary>
            [RepositoryItem("82cc06ee-5867-4062-af27-4731414f4de6")]
            public virtual Ranorex.Container PnlCommonParameters
            {
                get
                {
                    return _pnlcommonparametersInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlCommonParameters item info.
            /// </summary>
            [RepositoryItemInfo("82cc06ee-5867-4062-af27-4731414f4de6")]
            public virtual RepoItemInfo PnlCommonParametersInfo
            {
                get
                {
                    return _pnlcommonparametersInfo;
                }
            }

            /// <summary>
            /// The CommonContainerDesignContainerUCCommon item.
            /// </summary>
            [RepositoryItem("9bdab4a0-b68c-462d-8a7a-ee3d0ccc0578")]
            public virtual Ranorex.Container CommonContainerDesignContainerUCCommon
            {
                get
                {
                    return _commoncontainerdesigncontaineruccommonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CommonContainerDesignContainerUCCommon item info.
            /// </summary>
            [RepositoryItemInfo("9bdab4a0-b68c-462d-8a7a-ee3d0ccc0578")]
            public virtual RepoItemInfo CommonContainerDesignContainerUCCommonInfo
            {
                get
                {
                    return _commoncontainerdesigncontaineruccommonInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("afe5b183-7073-4720-8d69-63a41fc571b9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _masterranorexstudioadministratorInfo;
            RepoItemInfo _east6designinputInfo;
            RepoItemInfo _east6Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "afe5b183-7073-4720-8d69-63a41fc571b9", "")
            {
                _masterranorexstudioadministratorInfo = new RepoItemInfo(this, "MasterRanorexStudioAdministrator", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Master\\ -\\ Ranorex\\ Studio\\ \\(']", 30000, null, "b10f0b5c-c059-46f1-85cc-5d12d0943c57");
                _east6designinputInfo = new RepoItemInfo(this, "East6DesignInput", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='East 6 - [Design Input]']", 30000, null, "99ea79e1-f15a-4aa7-b99d-76795fea92f7");
                _east6Info = new RepoItemInfo(this, "East6", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='East 6']", 30000, null, "1fb620f9-11db-4488-ae9e-8ae7fd15c566");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("afe5b183-7073-4720-8d69-63a41fc571b9")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("afe5b183-7073-4720-8d69-63a41fc571b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MasterRanorexStudioAdministrator item.
            /// </summary>
            [RepositoryItem("b10f0b5c-c059-46f1-85cc-5d12d0943c57")]
            public virtual Ranorex.Button MasterRanorexStudioAdministrator
            {
                get
                {
                    return _masterranorexstudioadministratorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MasterRanorexStudioAdministrator item info.
            /// </summary>
            [RepositoryItemInfo("b10f0b5c-c059-46f1-85cc-5d12d0943c57")]
            public virtual RepoItemInfo MasterRanorexStudioAdministratorInfo
            {
                get
                {
                    return _masterranorexstudioadministratorInfo;
                }
            }

            /// <summary>
            /// The East6DesignInput item.
            /// </summary>
            [RepositoryItem("99ea79e1-f15a-4aa7-b99d-76795fea92f7")]
            public virtual Ranorex.Button East6DesignInput
            {
                get
                {
                    return _east6designinputInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The East6DesignInput item info.
            /// </summary>
            [RepositoryItemInfo("99ea79e1-f15a-4aa7-b99d-76795fea92f7")]
            public virtual RepoItemInfo East6DesignInputInfo
            {
                get
                {
                    return _east6designinputInfo;
                }
            }

            /// <summary>
            /// The East6 item.
            /// </summary>
            [RepositoryItem("1fb620f9-11db-4488-ae9e-8ae7fd15c566")]
            public virtual Ranorex.Button East6
            {
                get
                {
                    return _east6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The East6 item info.
            /// </summary>
            [RepositoryItemInfo("1fb620f9-11db-4488-ae9e-8ae7fd15c566")]
            public virtual RepoItemInfo East6Info
            {
                get
                {
                    return _east6Info;
                }
            }
        }

        /// <summary>
        /// The CytelArchitect2011AppFolder folder.
        /// </summary>
        [RepositoryFolder("9fd8e872-75b5-4d02-a6d6-2a4d5dee1252")]
        public partial class CytelArchitect2011AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitembdifferenceofmeansmn2sdiInfo;

            /// <summary>
            /// Creates a new CytelArchitect2011  folder.
            /// </summary>
            public CytelArchitect2011AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CytelArchitect2011", "/element[@controltypename='PopupContainer']", parentFolder, 30000, null, true, "9fd8e872-75b5-4d02-a6d6-2a4d5dee1252", "")
            {
                _menuitembdifferenceofmeansmn2sdiInfo = new RepoItemInfo(this, "MenuItemBDifferenceOfMeansMN2SDI", "element[@controltypename='MenuPanel']/contextmenu/menuitem[1]", 30000, null, "d37f526e-cf3d-49be-8406-cd11830619e3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9fd8e872-75b5-4d02-a6d6-2a4d5dee1252")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9fd8e872-75b5-4d02-a6d6-2a4d5dee1252")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemBDifferenceOfMeansMN2SDI item.
            /// </summary>
            [RepositoryItem("d37f526e-cf3d-49be-8406-cd11830619e3")]
            public virtual Ranorex.MenuItem MenuItemBDifferenceOfMeansMN2SDI
            {
                get
                {
                    return _menuitembdifferenceofmeansmn2sdiInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemBDifferenceOfMeansMN2SDI item info.
            /// </summary>
            [RepositoryItemInfo("d37f526e-cf3d-49be-8406-cd11830619e3")]
            public virtual RepoItemInfo MenuItemBDifferenceOfMeansMN2SDIInfo
            {
                get
                {
                    return _menuitembdifferenceofmeansmn2sdiInfo;
                }
            }
        }

        /// <summary>
        /// The MyDocumentsAppFolder folder.
        /// </summary>
        [RepositoryFolder("417467a6-b09d-421c-b086-340283711257")]
        public partial class MyDocumentsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tree100Info;

            /// <summary>
            /// Creates a new MyDocuments  folder.
            /// </summary>
            public MyDocumentsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyDocuments", "/form[@title='My Documents']", parentFolder, 30000, null, true, "417467a6-b09d-421c-b086-340283711257", "")
            {
                _tree100Info = new RepoItemInfo(this, "Tree100", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[2]/?/?/tree[@controlid='100']", 30000, null, "c76729d5-bee8-41b5-ad86-89c81321054c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("417467a6-b09d-421c-b086-340283711257")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("417467a6-b09d-421c-b086-340283711257")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tree100 item.
            /// </summary>
            [RepositoryItem("c76729d5-bee8-41b5-ad86-89c81321054c")]
            public virtual Ranorex.Tree Tree100
            {
                get
                {
                    return _tree100Info.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Tree100 item info.
            /// </summary>
            [RepositoryItemInfo("c76729d5-bee8-41b5-ad86-89c81321054c")]
            public virtual RepoItemInfo Tree100Info
            {
                get
                {
                    return _tree100Info;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("b551d97e-16bb-4b1d-bfd0-e0d7c4a9fff6")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cytelarchitect2011shortcutInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "b551d97e-16bb-4b1d-bfd0-e0d7c4a9fff6", "")
            {
                _cytelarchitect2011shortcutInfo = new RepoItemInfo(this, "CytelArchitect2011Shortcut", "?/?/list[@controlid='1']/listitem[@text~'^Cytel\\.Architect2011\\ -\\ Sho']", 30000, null, "ccb798e8-b4ae-4a67-8f45-2edefde11dca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b551d97e-16bb-4b1d-bfd0-e0d7c4a9fff6")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b551d97e-16bb-4b1d-bfd0-e0d7c4a9fff6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CytelArchitect2011Shortcut item.
            /// </summary>
            [RepositoryItem("ccb798e8-b4ae-4a67-8f45-2edefde11dca")]
            public virtual Ranorex.ListItem CytelArchitect2011Shortcut
            {
                get
                {
                    return _cytelarchitect2011shortcutInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CytelArchitect2011Shortcut item info.
            /// </summary>
            [RepositoryItemInfo("ccb798e8-b4ae-4a67-8f45-2edefde11dca")]
            public virtual RepoItemInfo CytelArchitect2011ShortcutInfo
            {
                get
                {
                    return _cytelarchitect2011shortcutInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("856aefe8-c82b-4e3e-aaa6-e108648c410f")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _supersuperiorityInfo;
            RepoItemInfo _listitem4Info;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "856aefe8-c82b-4e3e-aaa6-e108648c410f", "")
            {
                _supersuperiorityInfo = new RepoItemInfo(this, "SuperSuperiority", "listitem[@text='Super Superiority']", 30000, null, "2ecefbe6-d8b0-4821-bdb3-1bc77da52771");
                _listitem4Info = new RepoItemInfo(this, "ListItem4", "listitem[@text='4']", 30000, null, "c9e7c5ff-079e-4b2c-b33f-44c50fc3dabf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("856aefe8-c82b-4e3e-aaa6-e108648c410f")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("856aefe8-c82b-4e3e-aaa6-e108648c410f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SuperSuperiority item.
            /// </summary>
            [RepositoryItem("2ecefbe6-d8b0-4821-bdb3-1bc77da52771")]
            public virtual Ranorex.ListItem SuperSuperiority
            {
                get
                {
                    return _supersuperiorityInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SuperSuperiority item info.
            /// </summary>
            [RepositoryItemInfo("2ecefbe6-d8b0-4821-bdb3-1bc77da52771")]
            public virtual RepoItemInfo SuperSuperiorityInfo
            {
                get
                {
                    return _supersuperiorityInfo;
                }
            }

            /// <summary>
            /// The ListItem4 item.
            /// </summary>
            [RepositoryItem("c9e7c5ff-079e-4b2c-b33f-44c50fc3dabf")]
            public virtual Ranorex.ListItem ListItem4
            {
                get
                {
                    return _listitem4Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem4 item info.
            /// </summary>
            [RepositoryItemInfo("c9e7c5ff-079e-4b2c-b33f-44c50fc3dabf")]
            public virtual RepoItemInfo ListItem4Info
            {
                get
                {
                    return _listitem4Info;
                }
            }
        }

    }
#pragma warning restore 0436
}