///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MeanTreatmentMu_t03 recording.
    /// </summary>
    [TestModule("f0e1a1d2-6837-4950-8e05-0197b72066b4", ModuleType.Recording, 1)]
    public partial class MeanTreatmentMu_t03 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static MeanTreatmentMu_t03 instance = new MeanTreatmentMu_t03();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MeanTreatmentMu_t03()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MeanTreatmentMu_t03 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.LblMeanControl' at 71;13.", repo.MainWindow.PnlUserControlCollection.LblMeanControlInfo, new RecordItemIndex(0));
            repo.MainWindow.PnlUserControlCollection.LblMeanControl.Click("71;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>Me&an Control (µ</n><b>c</b><n>):</n>') on item 'MainWindow.PnlUserControlCollection.LblMeanControl'.", repo.MainWindow.PnlUserControlCollection.LblMeanControlInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.LblMeanControlInfo, "Text", "<n>Me&an Control (µ</n><b>c</b><n>):</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0') on item 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, "Text", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='White') on item 'MainWindow.PnlUserControlCollection.TxtMeanControl'.", repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtMeanControlInfo, "BackColor", "White");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
