///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Navigatetothedifferenceofmeandesign recording.
    /// </summary>
    [TestModule("4d2f7d9c-6b55-46cd-ad42-643e65f09035", ModuleType.Recording, 1)]
    public partial class Navigatetothedifferenceofmeandesign : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static Navigatetothedifferenceofmeandesign instance = new Navigatetothedifferenceofmeandesign();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Navigatetothedifferenceofmeandesign()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Navigatetothedifferenceofmeandesign Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.TwoSamples' at 33;55.", repo.MainWindow.TwoSamplesInfo, new RecordItemIndex(0));
            repo.MainWindow.TwoSamples.Click("33;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI' at 418;31.", repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDIInfo, new RecordItemIndex(1));
            repo.CytelArchitect2011.MenuItemBDifferenceOfMeansMN2SDI.Click("418;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.DesignContinuousEndpointTwoSample'.", repo.MainWindow.DesignContinuousEndpointTwoSampleInfo, new RecordItemIndex(2));
            Validate.Exists(repo.MainWindow.DesignContinuousEndpointTwoSampleInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
