///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SampleRecording recording.
    /// </summary>
    [TestModule("3cab7c10-d452-4c94-ace1-89564ccf4b5f", ModuleType.Recording, 1)]
    public partial class SampleRecording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static SampleRecording instance = new SampleRecording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SampleRecording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SampleRecording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Explorer1.CytelArchitect2011Shortcut' at 57;29.", repo.Explorer1.CytelArchitect2011ShortcutInfo, new RecordItemIndex(0));
            repo.Explorer1.CytelArchitect2011Shortcut.DoubleClick("57;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeDialog.BtnOK' at 50;15.", repo.WelcomeDialog.BtnOKInfo, new RecordItemIndex(2));
            repo.WelcomeDialog.BtnOK.Click("50;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.Open' at 6;10.", repo.MainWindow.OpenInfo, new RecordItemIndex(3));
            repo.MainWindow.Open.Click("6;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.SuperSuperiority' at 76;8.", repo.List1000.SuperSuperiorityInfo, new RecordItemIndex(4));
            repo.List1000.SuperSuperiority.Click("76;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.CmbLooks' at 28;14.", repo.MainWindow.CmbLooksInfo, new RecordItemIndex(5));
            repo.MainWindow.CmbLooks.Click("28;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItem4' at 8;5.", repo.List1000.ListItem4Info, new RecordItemIndex(6));
            repo.List1000.ListItem4.Click("8;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlUserControlCollection.TestParameters' at 103;9.", repo.MainWindow.PnlUserControlCollection.TestParametersInfo, new RecordItemIndex(7));
            repo.MainWindow.PnlUserControlCollection.TestParameters.Click("103;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.PnlCommonParameters.TxtPower' at 47;7.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(8));
            repo.MainWindow.PnlCommonParameters.TxtPower.MoveTo("47;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainWindow.PnlCommonParameters.TxtPower' at 55;-1.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(9));
            repo.MainWindow.PnlCommonParameters.TxtPower.MoveTo("55;-1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.PnlUserControlCollection.PnlCommonParameters' at 210;7.", repo.MainWindow.PnlUserControlCollection.PnlCommonParametersInfo, new RecordItemIndex(10));
            repo.MainWindow.PnlUserControlCollection.PnlCommonParameters.MoveTo("210;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.PnlCommonParameters.TxtPower' at 60;11.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(11));
            repo.MainWindow.PnlCommonParameters.TxtPower.Click("60;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.89' with focus on 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(12));
            repo.MainWindow.PnlCommonParameters.TxtPower.PressKeys(".89");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='.89') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "Text", ".89");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='Red') on item 'MainWindow.PnlCommonParameters.TxtPower'.", repo.MainWindow.PnlCommonParameters.TxtPowerInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.MainWindow.PnlCommonParameters.TxtPowerInfo, "BackColor", "Red");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
