///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StandardDeviationσ1 recording.
    /// </summary>
    [TestModule("b620bc00-ddb9-47a1-842d-7a4107560fe1", ModuleType.Recording, 1)]
    public partial class StandardDeviationσ1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static StandardDeviationσ1 instance = new StandardDeviationσ1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StandardDeviationσ1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StandardDeviationσ1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>Std. De&viation (σ):</n>') on item 'MainWindow.PnlUserControlCollection.LblStdDeviation'.", repo.MainWindow.PnlUserControlCollection.LblStdDeviationInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.LblStdDeviationInfo, "Text", "<n>Std. De&viation (σ):</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, "Text", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (BackColor='Pink') on item 'MainWindow.PnlUserControlCollection.TxtSigma'.", repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.TxtSigmaInfo, "BackColor", "Pink");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
