///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestType1Sided recording.
    /// </summary>
    [TestModule("81bfc4f3-df58-4381-8b73-afa2f395d6f3", ModuleType.Recording, 1)]
    public partial class TestType1Sided : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static TestType1Sided instance = new TestType1Sided();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestType1Sided()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestType1Sided Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>Te&st Type:</n>') on item 'MainWindow.PnlUserControlCollection.LblSideType'.", repo.MainWindow.PnlUserControlCollection.LblSideTypeInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.LblSideTypeInfo, "Text", "<n>Te&st Type:</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1-Sided') on item 'MainWindow.PnlUserControlCollection.CmbSideType'.", repo.MainWindow.PnlUserControlCollection.CmbSideTypeInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.CmbSideTypeInfo, "Text", "1-Sided");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedItem='1-Sided') on item 'MainWindow.PnlUserControlCollection.CmbSideType'.", repo.MainWindow.PnlUserControlCollection.CmbSideTypeInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.PnlUserControlCollection.CmbSideTypeInfo, "SelectedItem", "1-Sided");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
