///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Master
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025 recording.
    /// </summary>
    [TestModule("3a805164-20b5-4bf5-9c89-ceb5600c7b71", ModuleType.Recording, 1)]
    public partial class VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MasterRepository repository.
        /// </summary>
        public static MasterRepository repo = MasterRepository.Instance;

        static VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025 instance = new VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifytheinputparametersanditsdefaultvaluesdisplayedasbelowTypeIErrorα0025 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.LblTypeIError' at 60;15.", repo.MainWindow.LblTypeIErrorInfo, new RecordItemIndex(0));
            repo.MainWindow.LblTypeIError.Click("60;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='<n>Type I &Error (α):</n>') on item 'MainWindow.LblTypeIError'.", repo.MainWindow.LblTypeIErrorInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MainWindow.LblTypeIErrorInfo, "Text", "<n>Type I &Error (α):</n>");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.025') on item 'MainWindow.TxtTypeIError'.", repo.MainWindow.TxtTypeIErrorInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MainWindow.TxtTypeIErrorInfo, "Text", "0.025");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
